services:
  transport_layer:
    image: rogerfar/rdtclient
    container_name: lyra_transport
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ./data/transport:/data/db
      - /mnt/storage/ingest:/data/downloads
    ports:
      - "6500:6500"
    restart: unless-stopped

  network_node:
    image: slskd/slskd
    container_name: lyra_node
    environment:
      - SLSKD_REMOTE_CONFIGURATION=true
      - SLSKD_SLSK_LISTEN_PORT=50300
    volumes:
      - ./data/node/slskd.yml:/app/slskd.yml
      - ./data/node/data:/app/data
      - /mnt/storage/ingest:/app/downloads
    ports:
      - "5030:5030"
      - "50300:50300"
    restart: unless-stopped
